@id = 1GET http://localhost:3000/app/v1/appointmentStatus/findAll

###FIND ALL
GET http://localhost:3000/app/v1/appointmentStatus/findAll

### FIND ONE
GET http://localhost:3000/app/v1/appointmentStatus/findOne/{{id}}

### CREATE
POST http://localhost:3000/app/v1/appointmentStatus/create
Content-Type: application/json

{
  "appointment": "1760316126233uYaSSyhoCfPJUy",
  "observations": "El paciente llego 15 minutos tarde",
  "idTypeAppointmentStatus":"1760303705587yWcdh02HlZ2kPs"
}