@id = 1
###FIND ALL
GET http://localhost:3000/app/v1/appointmentStatus/findAll

### FIND ONE
GET http://localhost:3000/app/v1/appointmentStatus/findOne/{{id}}

### CREATE
POST http://localhost:3000/app/v1/appointmentStatus/create
Content-Type: application/json

{
  "observations": "Llega tarde 15 minutos",
  "idTypeAppointmentStatus":"2"
}