@id = e259834c-ee0c-4e49-847e-4f9f46379028
GET http://localhost:3000/app/v1/typeAppointmentStatus/findAll

### FIND ONE
GET http://localhost:3000/app/v1/typeAppointmentStatus/findOne/{{id}}

### CREATE
POST http://localhost:3000/app/v1/typeAppointmentStatus/create
Content-Type: application/json

{
  "name": "manutuso"
}
### UPDATE
PUT http://localhost:3000/app/v1/typeAppointmentStatus/update/{{id}}
Content-Type: application/json

{
  "name": "Laureano"
}