@id = 8dee950f-cfc7-49e8-a2e6-6dbbf2fc5f66

### FIND ALL
GET http://localhost:3000/app/v1/medicalSpecialty/findAll

### FIND ONE
GET http://localhost:3000/app/v1/medicalSpecialty/findOne/{{id}}


### CREATE
POST http://localhost:3000/app/v1/medicalSpecialty/create
Content-Type: application/json

{
  "name": "Medicina Familiar"
}

### UPDATE
POST http://localhost:3000/app/v1/medicalSpecialty/update/{{id}}

Content-Type: application/json

{
  "name": "Cirugía"
}

### REMOVE
DELETE http://localhost:3000/app/v1/medicalSpecialty/remove/{{id}}

